version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "host=postgres user=postgres password=postgres dbname=postgres sslmode=disable"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - web

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
